import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
    main : {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        height: '100%',
        // padding: 10,
    },
    background: {
        flex: 1,
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 15,
        paddingVertical : '10%',
    },
    button: {
        borderRadius:10,
        borderWidth: 2,
        margin: 10,
        alignItems: 'center',
        justifyContent: 'center',
        maxWidth: "80%",
    },
    newButton: {
        backgroundColor: "#b184e8",
        borderColor: "#d7bff5"
    },
    joinButton: {
        backgroundColor: "#f0afd2",
        borderColor: "#ffdbef"
    },
    slightButton: {
        borderWidth: 2,
        borderRadius: 30,
        // margin: 15,
        padding: 8,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: "#b184e8",
        borderColor: "#d7bff5",
    },
    slightButtonAdjust:  {
        // borderRadius:100,
        // maxWidth: "30%",
        padding: "unset",
    },
    buttonText: {
        color: "white",
        fontSize: 40,
        textShadowOffset:{width: 0, height: 0},
        textShadowRadius:10,
        paddingHorizontal: 10,
        fontFamily: Platform.OS === 'ios' ? 'Helvetica' : "sans-serif-light", //options: sans-serif-thin, normal
    },
    newText: {
        textShadowColor : "#9886b0",
        padding: 10,
    },
    joinText: {
        textShadowColor : "#c295ae",
        padding: 10,
    },
    buttonRow: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        width: '100%',
    },
    header: {
        fontSize: 60,
        fontWeight: 'bold',
        color:  '#723ca3', // '#170838',
        marginBottom: 20,
        fontFamily: Platform.OS === 'ios' ? 'HelveticaNeue-Thin' : "sans-serif-thin",
        textShadowOffset:{width: 0, height: 0},
        textShadowRadius: 5, //used to be 8
        textShadowColor : "white",
        textAlign: 'center',
    },
    newGamePopup: {
        flex: 1,
        justifyContent: 'center',
        width: '100%',
        height: '100%',
        padding: 25,
        marginBottom: 0,
    },
    textInput:{
        color: 'white',
        fontSize: 30,
        marginBottom: 20,
    },
    playerCountText: {
        color: 'black',
        fontSize: 30,
        fontWeight: 'bold',
        marginTop: 50,
        textShadowOffset:{width: 0, height: 0},
        textShadowRadius: 3, //used to be 8
        textShadowColor : "white",
        textAlign: 'center',
    },
    inputBox: {
        height: 60,
        borderWidth: 1,
        borderColor: 'white',
        color: 'white',
        paddingHorizontal: 10,
        borderRadius: 10,
        fontSize: 22,
        marginBottom: 20,
    },
    gameCode: {
        fontSize: 80,
    },
    instructionText: {
        fontSize: 30,
        color: 'white',
        // margin: 5,
        fontFamily: Platform.OS === 'ios' ? 'Helvetica' :  "sans-serif-medium",
    },
    overheadText: {
        fontSize: 35,
        color: 'black',
        // margin: 5,
        fontFamily: Platform.OS === 'ios' ? 'Helvetica' :  "sans-serif-medium",
        width: '100%',
        marginLeft: 10,
    },
    instructions: {
        fontSize: 38,
        color: 'white',
        margin: 5,
        // marginBottom: 40,
        fontFamily: Platform.OS === 'ios' ? 'Helvetica' : "sans-serif-medium",
    },
    answerContainer: {
        flex: 1,
        width: '100%',
        height: '100%',
    },
    promptHolder: {
        flex:5, 
        width:'100%',
        justifyContent: 'space-between',
        alignItems: 'stretch',
        paddingBottom:20,
    },
    promptHolder2: {
        flex:1, 
        width:'100%',
        // justifyContent: 'space-between',
        // alignItems: 'stretch',
        paddingVertical:10,
        
    },
    titleBox: {
        // flex: 1,
        borderRadius:10,
        borderWidth: 2,
        backgroundColor: "#9774c2",
        borderColor: "#d7bff5",
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 10,
        // marginVertical: 25,
        padding: 15,
        minHeight: 30, 
        // width: '100%',
        maxHeight: '70%',
    },
    allAnswersBox: {
        // flex: 3,
        paddingHorizontal: 15,
        paddingVertical: 20,
        paddingBottom: 50,
        width: '100%',
    },
    timerBox: {
        flex: 1,
        // minHeight: '30%',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        padding: 0,
        minHeight: 30,
    },
    timer: {
        fontSize: 80,
        fontFamily: Platform.OS === 'ios' ? 'Helvetica' :  "sans-serif-medium",
        fontWeight: 'bold',
    },
    adderBox: { 
        flex: 1, 
        width: '100%',
        paddingHorizontal:10,
        // minHeight: 100, 
        justifyContent: 'space-between',
        alignItems: 'center',
        flexDirection: 'row',
    },
    question: {
        fontSize: 25,
        color: 'white',
        margin: 5,
        fontFamily: Platform.OS === 'ios' ? 'Helvetica' :  "sans-serif-medium",
    },

    inputBoxQuestion: {
        backgroundColor: "#b184e8",
        flex: 5, 
        borderTopRightRadius:0,
        borderBottomRightRadius:0,
        borderRightWidth:0,
    },
    promptSubmitButton:{
        flex: 1, 
        height: 60,
        justifyContent: 'center', // Centers the child components (the arrow) vertically
        alignItems: 'center',
        marginBottom: 20,
        backgroundColor: "#8e6cb8",
        borderColor: "white",
        borderTopRightRadius:10,
        borderBottomRightRadius:10,
        borderWidth: 1,
    },
    promptRoundHeader: {
        fontSize: 20,
        color: 'white',
        margin: 10,
        fontFamily: Platform.OS === 'ios' ? 'Helvetica' :  "sans-serif-medium",
    },
    roundHeader: {
        fontSize: 20,
        color: 'black',
        marginHorizontal: 30,
        marginBottom: 10,
        fontFamily: Platform.OS === 'ios' ? 'Helvetica' :  "sans-serif-medium",
        fontWeight: 'bold',
        textAlign: 'right',
    },
    guessBox : {
        borderRadius:10,
        borderWidth: 2,
        backgroundColor: "#d2b8ff",
        borderColor: "#be9bfa",
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 10,
        padding: 5,
        minHeight: 20, 
        marginVertical: 10,
    },
    choosePlayerModal: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 7, 0.41)',
    },
    modalInnerContent: {
        width: '90%', 
        height: 'auto', 
        minHeight: '30%',
        // margin: 20, 
        backgroundColor: '#e1cafc', // '#9951db', 
        // borderColor: "#5c41a6",
        // borderWidth: 2,
        borderRadius: 10, 
        padding: 15,
        alignItems: 'center',
    },
    playersList: {
        alignItems: 'flex-start', 
        marginTop: 10,             
        fontSize: 20, 
        width: '100%',
        paddingHorizontal: 20,
        paddingVertical: 10,
        backgroundColor: '#cbb5e6',
        borderRadius: 10,
    },
    playerName: {
        fontSize: 30,
        color: 'white',
        fontWeight: 'bold',
    },
    underliner: {
        width: 80,
        height: 1, 
        backgroundColor: '#ab97c4', 
        marginTop: 5,
    },
    underlinerShort: {
        width: 50,
    },
    takenPlayer: {
        color: '#dedede',
        fontSize: 25,
    },
    totalScoreTag:  {
        top: 0,
        zIndex: -1, 
        backgroundColor: '#3f1c8a',
        padding: 5,
        minWidth: 120,
        maxWidth: 180,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        marginTop: -15,
        marginBottom: 15,
        alignSelf: 'flex-start',
        left: 40,
    },
    nameTag:  {
        top: 14,
        zIndex: -1, 
        backgroundColor: '#3f1c8a',
        padding: 5,
        minWidth: 120,
        maxWidth: 180,
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        marginTop: -15,
    },
    nameRight:{
        alignSelf: 'flex-end',
        right: 40,
        // alignSelf: 'flex-start',
        // left: 100,
    },
    nameLeft:{
        alignSelf: 'flex-start',
        left: 40,
    },
    nameTagText: {
        fontSize: 20,
        color: 'white',
    },
    voteBox: {
        top: 25,
        zIndex: 1, 
        marginTop: -35,
        alignSelf: 'flex-end',
        right: 5,
    },
    guessedBox: {
        top: 10,
        zIndex: 1, 
        marginTop: -22,
        marginBottom: 30,
        alignSelf: 'flex-start',
        left: 30,
    },
    favoriteBox: {
        top: 10,
        zIndex: 1, 
        marginTop: -28,
        alignSelf: 'flex-end',
        right: 25,
    },
    favoriteText: {
        fontSize: 22,
        color: '#037359',
        fontWeight: 'bold',
    },
    guessSubmitButton: {
        borderRadius:10,
        borderWidth: 2,
        backgroundColor: "#5c79fa",
        borderColor: "#4f6ef7",
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 10,
        padding: 10,
        paddingHorizontal: 20,
        marginVertical: 10,
    }



});

export default styles